# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20170326_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseset',
            name='choices',
            field=models.IntegerField(default=1),
        ),
    ]
