# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_courseset_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
